---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True

driver:
  name: docker

platforms:
  - name: master
    image: geerlingguy/docker-ubuntu2004-ansible
    privileged: true
    pre_build_image: true
    environment:
      POSTGRESQL_NODE_TYPE: "master"

  - name: replica
    image: geerlingguy/docker-ubuntu2004-ansible
    privileged: true
    pre_build_image: true
    environment:
      POSTGRESQL_NODE_TYPE: "replica"

provisioner:
  name: ansible
  lint: |
    yamllint .
    ansible-lint

scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: ansible
  lint: |
    ansible-lint
